server:
  port: 8099

spring:
  elasticsearch.datasource:
    driverClassName: org.elasticsearch.xpack.sql.jdbc.EsDriver
    url: jdbc:es://http://127.0.0.1:9200

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml


